= spring-cloud-config
:github: https://github.com/spring-cloud/spring-cloud-config
:githubmaster: {github}/tree/master
:docslink: {githubmaster}/docs/src/main/asciidoc
// :github: https://github.com/zhanliquan/docs-spring-cloud.git
// :githubmaster: {github}/tree/main
// :docslink: {githubmaster}/modules/spring-cloud-config/pages/
:toc: right
:source-highlighter: rouge
:special-string: _

== Quick Start

include::quickstart.adoc[]

== Spring Cloud Config Server

Spring Cloud Config Server provides an HTTP resource-based API for external configuration (name-value pairs or equivalent YAML content).
The server is embeddable in a Spring Boot application, by using the `@EnableConfigServer` annotation.
Consequently, the following application is a config server:

Spring Cloud Config Server 为外部配置(name-value对或者是等价的YAML内容)提供了一个基于HTTP访问资源的API。
通过使用 `@EnableConfigServer` 注解，服务可以嵌入到Spring Boot的应用中。
一个config server 应用如下:

.ConfigServer.java
[source,java]
----
@SpringBootApplication
@EnableConfigServer
public class ConfigServer {
  public static void main(String[] args) {
    SpringApplication.run(ConfigServer.class, args);
  }
}
----

Like all Spring Boot applications, it runs on port 8080 by default, but you can switch it to the more conventional port 8888 in various ways.
The easiest, which also sets a default configuration repository, is by launching it with `spring.config.name=configserver` (there is a `configserver.yml` in the Config Server jar).
Another is to use your own `application.properties`, as shown in the following example:

和所有的Spring Boot应用一样，它运行在默认的8080端口，但是你可以很多方式切换到更传统的8888端口。
最简单就是使用一个默认的配置文件，通过启动的时候指定 `spring.config.name=configserver` （configserver就是指向Config Server中的 `configserver.yml`)
其他方式也可以在 `application.properties` 中指定，例如显示如下：


.application.properties
[source,properties]
----
server.port=8888
spring.cloud.config.server.git.uri=file://${user.home}/config-repo
----

where `${user.home}/config-repo` is a git repository containing YAML and properties files.

`${user.home}/config-repo` 指向一个包含YAML和properties文件的git仓库。

NOTE: On Windows, you need an extra "/" in the file URL if it is absolute with a drive prefix (for example,`file:///${user.home}/config-repo`).

NOTE: 在Windows上，如果是绝对路劲，文件URL需要额外的加上一个前缀"/"（例如：`file:///${user.home}/config-repo`).

[TIP]
====
The following listing shows a recipe for creating the git repository in the preceding example:

可以通过如下的方式，为前面的例子创建git仓库：

----
$ cd $HOME
$ mkdir config-repo
$ cd config-repo
$ git init .
$ echo info.foo: bar > application.properties
$ git add -A .
$ git commit -m "Add application.properties"
----
====

WARNING: Using the local filesystem for your git repository is intended for testing only.
You should use a server to host your configuration repositories in production.

WARNING: 这是一个只为了测试创建的本地文件系统的git仓库。
最好在生产环境中使用服务器托管配置仓库。

WARNING: The initial clone of your configuration repository can be quick and efficient if you keep only text files in it.
If you store binary files, especially large ones, you may experience delays on the first request for configuration or encounter out of memory errors in the server.

WARNING: 如果在仓库中只保存文本文件，这样方便快速有效的初始化clone配置仓库。
如果存储了二进制文件，或特别大的文件，你可能请求配置文件的时候回延迟，在服务器遇到内存溢出（OOM）.

=== Environment Repository

Where should you store the configuration data for the Config Server?
The strategy that governs this behaviour is the `EnvironmentRepository`, serving `Environment` objects.
This `Environment` is a shallow copy of the domain from the Spring `Environment` (including `propertySources` as the main feature).
The `Environment` resources are parametrized by three variables:

在哪里存储Config Server的配置信息呢？
管理这种行为的策略是 `EnvironmentRepository`， 它提供 `Environment` 对象.
这个 `Environment` 是从Spring `Environment` (包括作为主要特征的 `propertySources`) 域的浅层拷贝。
The `Environment` 资源是由3变量作为参数:


* `{application}`, which maps to `spring.application.name` on the client side.
* `{profile}`, which maps to `spring.profiles.active` on the client (comma-separated list).
* `{label}`, which is a server side feature labelling a "versioned" set of config files.

Repository implementations generally behave like a Spring Boot application, loading configuration files from a `spring.config.name` equal to the `{application}` parameter, and `spring.profiles.active` equal to the `{profiles}` parameter.
Precedence rules for profiles are also the same as in a regular Spring Boot application: Active profiles take precedence over defaults, and, if there are multiple profiles, the last one wins (similar to adding entries to a `Map`).

仓库的实现通常表现像Spring Boot应用一样，从 `spring.config.name`（等于变量 `{application}`）和 `spring.profiles.active`（等于变量 `{profiles}` ）加载配置文件。
配置文件的优先规则也与常规 Spring Boot 应用程序相同：配置文件优先于默认配置，如果有多个配置文件，则最后一个优先（类似于将条目添加到 Map）。

The following sample client application has this bootstrap configuration:

[source,yaml]
----
spring:
  application:
    name: foo
  profiles:
    active: dev,mysql
----

(As usual with a Spring Boot application, these properties could also be set by environment variables or command line arguments).

If the repository is file-based, the server creates an
`Environment` from `application.yml` (shared between all clients) and
`foo.yml` (with `foo.yml` taking precedence).
If the YAML files have documents inside them that point to Spring profiles, those are applied with higher precedence (in order of the profiles listed).
If there are profile-specific YAML (or properties) files, these are also applied with higher precedence than the defaults.
Higher precedence translates to a `PropertySource` listed earlier in the `Environment`.
(These same rules apply in a standalone Spring Boot application.)

You can set spring.cloud.config.server.accept-empty to false so that Server would return a HTTP 404 status, if the application is not found.By default, this flag is set to true.

==== Git Backend

The default implementation of `EnvironmentRepository` uses a Git backend, which is very convenient for managing upgrades and physical environments and for auditing changes.
To change the location of the repository, you can set the `spring.cloud.config.server.git.uri` configuration property in the Config Server (for example in `application.yml`).
If you set it with a `file:` prefix, it should work from a local repository so that you can get started quickly and easily without a server. However, in that case, the server operates directly on the local repository without cloning it (it does not matter if it is not bare because the Config Server never makes changes to the "remote" repository).
To scale the Config Server up and make it highly available, you need to have all instances of the server pointing to the same repository, so only a shared file system would work.
Even in that case, it is better to use the `ssh:` protocol for a shared filesystem repository, so that the server can clone it and use a local working copy as a cache.

This repository implementation maps the `{label}` parameter of the HTTP resource to a git label (commit id, branch name, or tag).
If the git branch or tag name contains a slash (`/`), then the label in the HTTP URL should instead be specified with the special string `({special-string})` (to avoid ambiguity with other URL paths).
For example, if the label is `foo/bar`, replacing the slash would result in the following label: `foo({special-string})bar`.
The inclusion of the special string `({special-string})` can also be applied to the `{application}` parameter.
If you use a command-line client such as curl, be careful with the brackets in the URL -- you should escape them from the shell with single quotes ('').


== Serving Plain Text
== Embedding the Config Server
== Push Notifications and Spring Cloud Bus
== Spring Cloud Config Client
